print("Hello user")
a=int(input("Are you planing for a vacation?, Type 1 for yes 2 for no:- "))
if a == 1:
    print("We are here to help you out")
    print("Tell us your Intrests from the given list:- ")
    print("1= Mountains")
    print("2= Beaches")
    print("3= National Parks")
    print("4= Historical Cities")
    print("5= Heritage Sites")
    print("6= Art and Museums")
    print("7= Desert")
    b =int(input("Enter Your Intrest no:- "))
    if b== 1:
        print("1. Leh-Ladakh (Jammu & Kashmir):-")
        print("Why it’s the best: Known for its stunning high-altitude desert landscapes, Ladakh offers some of the most breathtaking views in India. It’s a paradise for adventure enthusiasts, with activities like trekking, biking, and river rafting. The unique culture and monasteries add to the charm.")
        print("Best time to visit: May to September.")
        print("2. Manali (Himachal Pradesh)")
        print("Why it’s the best: A year-round destination, Manali offers a mix of adventure sports like skiing and paragliding in winter, and trekking and river rafting in summer. The picturesque views, along with nearby attractions like Solang Valley and Rohtang Pass, make it a must-visit.")
        print("Best time to visit: December to February (snow) and March to June (pleasant weather).")
        print("3. Shimla (Himachal Pradesh)")
        print("Why it’s the best: Known as the 'Queen of Hills' Shimla is famous for its colonial architecture, pleasant climate, and scenic beauty. It’s perfect for a family getaway, offering relaxed strolls along Mall Road and scenic spots like Kufri and Jakhoo Temple.")
        print("Best time to visit: March to June and December to January (for snowfall).")
        print("4. Darjeeling (West Bengal)")
        print("Why it’s the best: This hill station offers mesmerizing views of the Kanchenjunga, lush tea gardens, and a colonial charm. The famous Toy Train ride, along with attractions like Tiger Hill and Peace Pagoda, makes it a great mix of adventure and serenity.")
        print("Best time to visit: March to June and September to November.")
        print("5. Sikkim (Sikkim)")
        print("Why it’s the best: Sikkim is a hidden gem known for its stunning views of the Kanchenjunga, monasteries, and lush valleys. Whether it’s trekking to Goecha La or visiting Tsomgo Lake, Sikkim is a perfect blend of natural beauty and cultural heritage.")
        print("Best time to visit: March to June and September to December.")
        print("Thank you!!")
    elif b== 2:
        print("1. Goa")
        print("Why it’s the best: Goa is India's most popular beach destination, known for its stunning beaches, vibrant nightlife, and laid-back atmosphere. From the bustling Baga and Anjuna beaches to the serene Palolem and Agonda, Goa offers something for everyone.")
        print("Best time to visit: November to March.")
        print("2. Andaman & Nicobar Islands")
        print("Why it’s the best: The Andaman & Nicobar Islands offer pristine, untouched beaches with crystal-clear waters and coral reefs, perfect for snorkeling and diving. Havelock Island, with Radhanagar Beach, is one of the most beautiful in Asia.")
        print("Best time to visit: October to May.")
        print("3. Kerala (Varkala, Kovalam, Alleppey)")
        print("Why it’s the best: Kerala’s beaches, like Varkala and Kovalam, are famous for their scenic beauty and peaceful vibes. Varkala offers cliffs overlooking the Arabian Sea, while Kovalam has a crescent-shaped beach ideal for relaxation and water sports. Alleppey’s backwaters are another unique attraction.")
        print("Best time to visit: November to March.")
        print("4. Gokarna (Karnataka)")
        print("Why it’s the best: Gokarna is a quieter, less commercialized alternative to Goa. It is famous for its serene, beautiful beaches like Om Beach and Kudle Beach, which are perfect for those seeking peace and natural beauty.")
        print("Best time to visit: November to March.")
        print("5. Pondicherry")
        print("Why it’s the best: Pondicherry combines French colonial charm with beautiful beaches like Paradise Beach and Serenity Beach. The relaxed vibe, along with opportunities for water sports, makes it a great beach destination with a cultural twist.")
        print("Best time to visit: October to March.")
        print("Thank you!!")
    elif b== 3:
        print("1. Jim Corbett National Park (Uttarakhand)")
        print("Why it’s the best: India’s first national park, Jim Corbett is a haven for wildlife enthusiasts. It is famous for its population of Bengal tigers, along with elephants, leopards, and diverse bird species.")
        print("Best time to visit: November to June.")
        print("2. Kaziranga National Park (Assam)")
        print("Why it’s the best: Known for its population of one-horned rhinoceroses, Kaziranga is a UNESCO World Heritage Site. It is home to a rich diversity of wildlife, including tigers, elephants, and wild buffaloes.")
        print("Best time to visit: November to April.")
        print("3. Bandhavgarh National Park (Madhya Pradesh)")
        print("Why it’s the best: Famous for having one of the highest densities of Bengal tigers in the world, Bandhavgarh offers great opportunities for tiger sightings. The park also has a rich history and stunning landscapes.")
        print("Best time to visit: October to June.")
        print("4. Sundarbans National Park (West Bengal)")
        print("Why it’s the best: The Sundarbans is known for its unique mangrove forests and as the habitat of the Bengal tiger. It is a UNESCO World Heritage Site and one of the largest tidal halophytic mangrove forests in the world.")
        print("Best time to visit: November to February.")
        print("5. Ranthambhore National Park (Rajasthan)")
        print("Why it’s the best: Ranthambhore is famous for its majestic tigers, and the park also boasts a rich history with ancient forts and temples. It’s one of the best places in India to spot tigers in the wild.")
        print("Best time to visit: October to April.")
        print("Thank you!!")
    elif b== 4:
        print("1. Jaipur (Rajasthan)")
        print("Why it’s the best: Known as the 'Pink City,' Jaipur is famous for its stunning palaces, forts, and vibrant markets. Key attractions include the Amber Fort, City Palace, Hawa Mahal, and Jantar Mantar.")
        print("Best time to visit: October to March.")
        print("2. Agra (Uttar Pradesh)")
        print("Why it’s the best: Home to the iconic Taj Mahal, Agra is a city steeped in Mughal history. Along with the Taj Mahal, the Agra Fort and Fatehpur Sikri are must-visit historical sites.")
        print("Best time to visit: October to March.")
        print("3. Delhi (Delhi NCR)")
        print("Why it’s the best: Delhi, India’s capital, is a blend of ancient history and modernity. Historical landmarks include the Red Fort, Qutub Minar, India Gate, Humayun's Tomb, and Jama Masjid.")
        print("Best time to visit: October to March.")
        print("4. Varanasi (Uttar Pradesh)")
        print("Why it’s the best: Known as the spiritual heart of India, Varanasi is one of the oldest continuously inhabited cities in the world. It’s famous for the ghats along the Ganges, Kashi Vishwanath Temple, and its rich cultural and religious heritage.")
        print("Best time to visit: October to March.")
        print("5. Mysore (Karnataka)")
        print("Why it’s the best: Mysore is renowned for its royal history, beautiful palaces, and temples. The Mysore Palace, Chamundi Hill, and the Mysore Zoo are key attractions, and the city is also famous for its Dussehra celebrations.")
        print("Best time to visit: October to March.")
        print("Thank you!!")
    elif b== 5:
        print("1. Taj Mahal (Agra, Uttar Pradesh)")
        print("Why it’s the best: The Taj Mahal, one of the Seven Wonders of the World, is a stunning example of Mughal architecture and a symbol of love. Its white marble beauty, gardens, and intricate designs make it a must-visit heritage site.")
        print("Best time to visit: October to March.")
        print("2. Qutub Minar (Delhi)")
        print("Why it’s the best: The Qutub Minar is the tallest brick minaret in the world, standing as a testament to the architectural brilliance of the Delhi Sultanate. It’s a UNESCO World Heritage Site and one of Delhi's most iconic landmarks.")
        print("Best time to visit: October to March.")
        print("3. Red Fort (Delhi)")
        print("Why it’s the best: A stunning example of Mughal architecture, the Red Fort was the main residence of the Mughal emperors for around 200 years. It’s a UNESCO World Heritage Site and a symbol of India’s rich history and independence.")
        print("Best time to visit: October to March.")
        print("4. Elephanta Caves (Mumbai, Maharashtra)")
        print("Why it’s the best: The Elephanta Caves, located on Elephanta Island near Mumbai, are a UNESCO World Heritage Site that showcase ancient rock-cut temples and sculptures dedicated to Hindu gods. The island offers a unique historical experience.")
        print("Best time to visit: November to February.")
        print("5. Khajuraho Group of Monuments (Madhya Pradesh)")
        print("Why it’s the best: Famous for its exquisite temples and stunning sculptures, the Khajuraho Group of Monuments is a UNESCO World Heritage Site known for its intricate and diverse depictions of art, architecture, and culture from the Chandela dynasty.")
        print("Best time to visit: October to March.")
        print("Thank you!!")
    elif b== 6:
         print("1. The National Museum (New Delhi)")
         print("Why it’s the best: The National Museum in Delhi is one of the largest museums in India, housing a vast collection of art, artifacts, and sculptures from different periods of Indian history, including the Indus Valley Civilization, Mughal art, and Buddhist artifacts.")
         print("Best time to visit: October to March.")
         print("2. Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (Mumbai, Maharashtra)")
         print("Why it’s the best: Known as the Prince of Wales Museum, this museum in Mumbai is an architectural marvel and houses a remarkable collection of sculptures, decorative arts, ancient manuscripts, and artifacts from India and beyond, including ancient Indian art and textiles.")
         print("Best time to visit: October to March.")
         print("3. The Indian Museum (Kolkata, West Bengal)")
         print("Why it’s the best: Founded in 1814, The Indian Museum is one of the oldest museums in India. It boasts extensive collections ranging from archaeology, art, and geology to zoology, making it a must-visit for history and art lovers.")
         print("Best time to visit: October to March.")
         print("4. National Gallery of Modern Art (New Delhi and Mumbai)")
         print("Why it’s the best: The National Gallery of Modern Art has branches in both Delhi and Mumbai. It houses an impressive collection of modern and contemporary Indian art, including works by iconic Indian artists such as Raja Ravi Varma, Amrita Sher-Gil, and more.")
         print("Best time to visit: October to March.")
         print("5. Salar Jung Museum (Hyderabad, Telangana)")
         print("Why it’s the best: One of the largest art museums in India, the Salar Jung Museum in Hyderabad is known for its vast collection of artifacts, including sculptures, textiles, manuscripts, and European and Asian paintings. It also houses the famous 'Veiled Rebecca' sculpture.")
         print("Best time to visit: October to March.")
         print("Thank you!!")
    elif b== 7:
        print("1. Jaisalmer (Rajasthan)")
        print("Why it’s the best: Known as the 'Golden City' due to its yellow sandstone architecture, Jaisalmer offers a mesmerizing desert experience. Visit the iconic Jaisalmer Fort, Patwon Ki Haveli, and enjoy a camel safari in the Sam Sand Dunes.")
        print("Best time to visit: October to March.")
        print("2. Pushkar (Rajasthan)")
        print("Why it’s the best: Pushkar is a small desert town known for its sacred Pushkar Lake and the famous Pushkar Camel Fair. The surrounding sand dunes offer camel rides and beautiful sunsets.")
        print("Best time to visit: October to March.")
        print("3. Rann of Kutch (Gujarat)")
        print("Why it’s the best: The Rann of Kutch is a vast salt desert that becomes a wonderland during the Rann Utsav, showcasing vibrant culture, art, and crafts. It’s also famous for its surreal white desert landscape.")
        print("Best time to visit: November to February.")
        print("4. Jodhpur (Rajasthan)")
        print("Why it’s the best: Known as the 'Blue City,' Jodhpur offers a blend of rich history and desert beauty. Explore Mehrangarh Fort and Umaid Bhawan Palace, and enjoy camel safaris in the surrounding desert.")
        print("Best time to visit: October to March.")
        print("5. Bikaner (Rajasthan)")
        print("Why it’s the best: Bikaner is renowned for its historical forts, palaces, and desert experiences. The Junagarh Fort and Karni Mata Temple (Rat Temple) are key attractions, and camel rides in the desert are a must-do.")
        print("Best time to visit: October to March.")
        print("Thank you!!")
else:
    print("We respect your Decision, Thank you")





